### ISSUE TITLE
JDT formatter options

### ISSUE THREAD

**Issue by victorolinasc** [yveszoundi/eglot-java#26]
Hi! Awesome package and much appreciated :)

Small tweaks here would make it perfect for my use cases:
- build.gradle.kts auto detection (I believe this is quite simple looking through the code, but am not certain of it)
- a wiki to help setting up eclipse JDT formatter options (and maybe some quick tips for auto-format hooked into eglot-format)

These are small things... I am always wondered by the Emacs evolution in recent years! 

I am currently in a Termux session so can't really try to open a PR easilly here but I might try it in the future. Leaving this here for reference if anyone can do it before me (which might take a while since I am no pro in Elisp).

Thanks once again for your work! Happy incoming new year!

**Comment by yveszoundi** [comment]
I moved the Kotlin gradle support concerns to another ticket (https://github.com/yveszoundi/eglot-java/issues/27).

It seems that this should be addressed in https://github.com/yveszoundi/eglot-java/issues/9 and maybe this ticket is about relevant documentation.

### About formatter options

#### Notes

There are several options (including formatter settings), that an "advanced user" might want to customize (See https://github.com/yveszoundi/eglot-java/issues/9 and https://github.com/joaotavora/eglot/discussions/1185 for an exhaustive list of options). 

I'd also expect that people will want to override occasionally settings per project, likely via [dir-local variables](https://www.gnu.org/software/emacs/manual/html_node/emacs/Directory-Variables.html).

#### Potential implementation

Maybe a custom variable called `eglot-java-initialization-options` can do the trick? This could be merged with default settings inside the function `cl-defmethod eglot-initialization-options ((server eglot-java-eclipse-jdt)`.

### About some wiki documentation

I'm a bit reluctant because I don't code professionally that much anymore (and usually not in Java nowadays).
- Without bug reports, I won't notice immediately Java related changes (Eclipse JDT LS or JVM or even `eglot`)
- I don't know if having a wiki is sustainable, without community support to keep it up to date

**Comment by yveszoundi** [comment]
Users need to be able to add custom `plist` entries to the value returned by `eglot-initialization-options` (add or override key value pairs).

More concretely speaking, users will want to hook code similar to the excerpt below inside `eglot-initialization-options`. 

```
....
:format ( :settings (:url "https://raw.githubusercontent.com/google/styleguide/gh-pages/eclipse-java-google-style.xml")
      ;; :settings (:url ,(expand-file-name (locate-user-emacs-file ".local/eclipse-java-google-style.xml")))
      ;; :onType (:enabled t)
      :enabled t)
....
```

For a general about what's involved see https://git.sr.ht/~theo/dotfiles/tree/ae2e9d0fbe1e5d0711b1b1c574d91ba9705b1b40/item/emacs/.emacs.d/lisp/eglot-java.el#L108. 

This is also why I think that this specific formatter configuration issue should be addressed in #9.

**Comment by yveszoundi** [comment]
Instead of formatter profiles, it's also possible to provide [additional settings](https://github.com/eclipse-jdtls/eclipse.jdt.ls/wiki/Language-Server-Settings-&-Capabilities#java-formatter-options) inside a properties file.

**Comment by yveszoundi** [comment]
@victorolinasc , I added a callback function to allow further customization for settings such as formatting.

Please check the relevant documentation https://github.com/yveszoundi/eglot-java#lsp-server-initialization-options
- There's an example for setting the Google style of formatting that you can leverage with `M-x eglot-format` afterwards
- For all the potential settings and their values, you can consult the [Eclipse JDT LS reference initialization schema](https://github.com/eclipse-jdtls/eclipse.jdt.ls/wiki/Running-the-JAVA-LS-server-from-the-command-line#initialize-request)
- There are tons of settings that some people could potentially be interested in, based on what I see in the schema.
- There are also [extended capabilities](https://github.com/eclipse-jdtls/eclipse.jdt.ls/wiki/Language-Server-Settings-&-Capabilities#extended-client-capabilities), some of them could require custom emacs-lisp handling.
