### ISSUE TITLE
Discussion: run/debug configurations

### ISSUE THREAD

**Issue by MagielBruntink** [yveszoundi/eglot-java#32]
Now that with eglot-java it's possible to easily run main classes and test classes/methods, I would like to understand how it could support specific configurations for such runs.

The following come to mind:
 - environment vars
 - main class args
 - other JVM args

One specific case is for projects that use Lombok. With the following in `.dir-locals.el` we can convince `jdtls` to process Lombok's annotations:
```
((nil . ((eval . (setq-local eglot-java-eclipse-jdt-args
                             (push (concat "-javaagent:" "/PATH/TO/lombok.jar")
                                   eglot-java-eclipse-jdt-args))))))
```

I wonder whether `.dir-locals.el` is a good mechanism to set Java run configurations in general. For main class args that doesn't seem very convenient, but for environment vars and JVM args it may be.

What are you thoughts?

**Comment by yveszoundi** [comment]
`tl;dr` _I like your changes but need to think more about the level of flexibility for running main classes._

I think that for environment variables and to an extent JVM args, directory local variables are preferred (via `.dir-locals.el`). Otherwise, it increases the "complexity" by introducing concepts or variables that are not necessarily needed in my opinion.
 
Following your current pull request, I like injecting by some specific jvm arguments, when the universal prefix is present (`C-u`). 
- I think that your `eglot-java-debug-jvm-arguments` works well in the context of tests
- I would add a separate variable for running main classes
  - I wouldn't necessarily use the same jvm arguments for running tests and main classes by default. With 2 variables, I have some level flexibility.
  - If running a main class, 
    - I might have a bunch of arguments that I want to provide, depending on the type of program (webapp, CLI, etc.)
    - I might also occasionally be happy with just few JVM parameters and no additional program arguments. When coding was still my main responsibility professionally, I was gradually using the debugger less (unless I had "no other option"). So any JVM parameters used for running main classes were often different in tests.

**Comment by yveszoundi** [comment]
@MagielBruntink, closing this issue as relevant changes were implemented.

Please reopen the issue if something was missed.
