### ISSUE TITLE
A new eglot process is started for each project in a Gradle multi-project

### ISSUE THREAD

**Issue by hennes-maertins** [yveszoundi/eglot-java#33]
I use eglot-java with a Gradle multi-project. For [example](https://github.com/hennes-maertins/simple-gradle-multi-project-example) the sub-projects are named "lib" and "app". I visit a Java file of project "lib" and enable eglot-java-mode. This starts a jdtls process. I visit a Java file of project "app" and enable eglot-java-mode. This starts another jdtls process. So there are two jdtls processes running in parallel. When I do the same just with eglot-mode itself, only one jdtls process is running.

For projects with a lot of sub-projects a lot of memory might be allocated. Is there a way to achieve that only one process is started for the whole multi-project? 

I guess the function `eglot-java--project-try` is involved because it finds the Gradle build file of the sub-project. This function is added to the `project-find-functions` by `eglot-java--init`.

**Comment by yveszoundi** [comment]
Thanks for the bug report, I'll take a look soon with your example project as reference. 

On top of my head, I don't know for a fact that a root project and its sub-modules can share the same jdtls instance with eglot.

- The `eglot-java--project-try` was extracted from the previously built-in Java support in `eglot` (a while back). 
  - I'll need to check how `jdtls` behaves in the absence of that
  - I don't know if removing that function will also have other inadvertent side-effects
- I'd expect the same behavior for multi-module Maven projects (I'll double-check).

**Comment by yveszoundi** [comment]
I think that what I have in mind below will work with minimal changes per "quick" tests. Please re-open the issue if needed.

#### Assessment
Removing `eglot-java--project-try` in the context of a versioned-control project works with a single eglot process.
- This is because of the default integration of `project.el` with known revision control systems
- In projects that are not yet under version control, no project will be detected (no code completion issues, etc.)

#### Overall Mitigation Approach
The proposed solution is to ensure that `eglot-java--project-try` is in last priority in the `project-find-functions` list. 
- That means that if a multi-module project is already under version control, the same eglot instance will be reused.
- Otherwise, it'll fallback to the original behavior with `eglot-java--project-try` 

#### Advanced functionality
In the worst case scenario, advanced users can add their own custom functions to `project-find-functions`.

**Comment by hennes-maertins** [comment]
Hello @yveszoundi, I have checked out the new version of eglot-java from melpa. I have tested it with a large Gradle project which contains of a lot of sub-projects. It works very well. Thank you very much!

**Comment by yveszoundi** [comment]
Great! Thanks for the follow-up and testing on your end.
